version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: yapeame
      POSTGRES_USER: emerson
      POSTGRES_PASSWORD: emerson123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - kafka

volumes:
  postgres_data:
